version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db   
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - 3112:3112
  graphql-server:
    build: ./graphql-server
    env_file: ./graphql-server/.env
    ports:
      - 4000:4000      